### PR TITLE
Show Seed if requested. Fixes #37

### LINKED ISSUE #37: Show Seed when run with --randomize
At the moment this runner swallows all jest output. 
When run with --randomize and (with or without --showSeed) the seed is not visible.
This makes it hard/impossible to rerun the test with the same seed because it is not visible.

### PR DESCRIPTION
**Pull request by tkalmar**

### CODE REVIEW

**Comment by rickhanlonii** [comment]
Got a screenshot? For test passing and failing.

**Comment by tkalmar** [comment]
grafik

Passing top, failing bottom.

**Comment by tkalmar** [comment]
@rickhanlonii ping ;)

**Comment by rickhanlonii** [comment]
Ah nice

**Comment by rickhanlonii** [comment]
Published as 0.6.0 https://github.com/rickhanlonii/jest-silent-reporter/releases/tag/0.6.0

**Pull request merged**
