### PR TITLE
Summary is now being printed on run complete

### PR DESCRIPTION
**Pull request by Asaf-S**

### CODE REVIEW

**Comment by rbelev** [comment]
Would love to be able to use this. Any issue in this moving forward? 😄

**Comment by Asaf-S** [comment]
I think the owner of this plugin is not maintaining this plugin anymore. Anyway, you can use my fork (which is waiting to be merged) by installing it directly from GitHub, as it was not registered independently to npm. I use it like that and it's really improved my testing experience...

Tell me if you'll need help setting it up.

**Comment by rickhanlonii** [comment]
@Asaf-S sorry for the delay. Printing the summary by default would defeat my purpose for this reporter. Can you add an option for this? Same as `showWarnings` but as `showSummary`?

**Comment by mrazauskas** [comment]
Since Jest [v28.0.0-alpha.9](https://github.com/facebook/jest/releases/tag/v28.0.0-alpha.9) one can add summary to Silence Reporter simply like this:

```
reporters: ['jest-silent-reporter', 'summary']
```

The default reporter will be disabled, only summary will print. Thanks for idea @Asaf-S!

**Comment by rickhanlonii** [comment]
@mrazauskas that's really cool, thanks for doing that!

Closing this as that's now the preferred way to opt-into a summary at the end.

**Comment by Asaf-S** [comment]
@mrazauskas - hey man, thx for the above only now have I noticed it!
It causes another problem now, I've opened an issue about it: [here](https://github.com/facebook/jest/issues/14009).
Would really appreciate it if you'll have a look.
Thx again.

**Comment by mrazauskas** [comment]
Sure. Saw your issue and looking at it already.

Interestingly Jest is using silent reporter with dummy and collects coverage in CI. See config: https://github.com/facebook/jest/blob/main/jest.config.ci.mjs

I will check if that really works and what is going on with your case.

**Comment by Asaf-S** [comment]
I think this is the quickest response for an issue ever. Can you be more awesome?? 😆

**Pull request closed without merging**
