### PR TITLE
feat: add an option for showing test paths

### PR DESCRIPTION
**Pull request by kdmadej**
This reporter is exactly what I've been looking for, but I missed the suites' paths for easier navigation 😉

### CODE REVIEW

**Comment by SimenB** [comment]
I think we should always show the path, no need for an option.

@rickhanlonii right?

**Comment by kdmadej** [comment]
I concur that would make more sense. I'll also change it so that instead of a full path, a relative one is shown like in the default reporter.

**Comment by rickhanlonii** [comment]
Yeah that makes sense as a default, no option!

**Review by rickhanlonii — APPROVED** [review]
LGTM!

**Comment by rickhanlonii** [comment]
Published in 0.2.1 👍

**Pull request merged**
